### ISSUE TITLE
saran

### ISSUE THREAD

**Issue by Bawazier** [rantaudev/meeting#1]
mungking bisa dijelasin juga tentang teknologi awal kita yaitu _GatsbyJS_ dan kenapa memilih teknologi tersebut dan seputar _JAMstack_

**Comment by andriawan** [comment]
ide bagus. Ini sebaiknya kita diskusikan secara teknis sih mas @Bawazier. Pemilihan awal Gatsby murni karena pendapat pribadi saya karena memang agak ribet kalau harus nyiapin satu set server sekaligus. Dengan Gatsby ini saya coba memangkas birokrasi tersebut dan berfokus pada konten dan tampilan. Kedepan mungkin kita bisa pertimbangkan penggunan stack lain jika memang dibutuhkan.

**Comment by Bawazier** [comment]
Iya bener, sesuai yg disampaikan mas @andriawan saat meeting. 
Maksud saya biar yang tidak ikut meeting bisa tau juga tentang yang mas jelaskan ini. Biar rantaudev bisa satu tujuan itu aja sih mas hehehe:grin:

**Comment by andriawan** [comment]
Iya mas @Bawazier, untuk bagian itu memang sepertinya belum saya masukin di highlights 😬. Mas @Bawazier mungkin mau coba PR (Pull Request) buat nambahin point itu di meeting pertama.
