### ISSUE TITLE
saran

### ISSUE THREAD

**Issue by Rahmatulah12** [rantaudev/meeting#2]
kalau bisa, kita membuat flow dan tugas2x pertama tentang pengembangan website yang akan rantau dev gunakan.
pertanyaan juga sih.
kalau saya dan teman2x mempunyai project or library or package dan bersedia diopen source kan, apakah dapat dipush ke git rantau dev?

**Comment by andriawan** [comment]
sangat bagus itu mas @Rahmatulah12. Untuk flow pengembangan website kita akan pake basis issue yang disediakan github mas @Rahmatulah12. Sudah paham alur PR kode mas @Rahmatulah12?

**Comment by Rahmatulah12** [comment]
nge pull maksudnya?

**Comment by andriawan** [comment]
mengajukan perubahan ke repo mas... Pull Requests https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
